steps:
  # 1. Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}', '.']

  # 2. Artifact Registryへのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}']

  # 3. Terraformの実行
  - name: 'hashicorp/terraform:light'
    args: ['init']
    dir: 'terraform/'
  - name: 'hashicorp/terraform:light'
    args: ['apply', '-auto-approve']
    dir: 'terraform/'

substitutions:
  _PROJECT_ID: ''
  _REPOSITORY: ''
  _IMAGE_NAME: ''
  _REGION: 'asia-northeast1'
