name: Direct Cloud Build with Workload Identity Federation
on: workflow_dispatch

env:
  PROJECT_ID: 'tutorial-emata-direct-wif2'
  PROJECT_NUM: '809358225314'
  REPOSITORY: 'my-docker-repo'
  GITHUB_REPO: 'tutorial-emata-direct-wif2'
  WORKER_POOL_NAME: 'gha-wif-vpcsc-build-private-pool'
  REGION: 'asia-northeast1'
jobs:
  get_secret:
    name: Get Secret from Secret Manager
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        workload_identity_provider: 'projects/${{ env.PROJECT_NUM }}/locations/global/workloadIdentityPools/github/providers/${{ env.GITHUB_REPO }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'

    - name: 'Get Secret'
      run: gcloud secrets versions access latest --secret="my-secret"

    - name: 'Build and Push Docker Image'
      run: |
        gcloud builds submit \
          --project=${{ env.PROJECT_ID }} \
          --tag asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/my-image \
          --gcs-log-dir='gs://${{ env.PROJECT_ID }}_cloudbuild/logs' \
          --worker-pool=projects/${{ env.PROJECT_ID }}/locations/${{ env.REGION }}/workerPools/${{ env.WORKER_POOL_NAME}} \
          --verbosity debug
