name: Get Secret
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  SERVICE_ACCOUNT_EMAIL: 'github-actions-impersonated-sa@tutorial-emata-direct-wif.iam.gserviceaccount.com'
  PROJECT_ID: 'tutorial-emata-direct-wif2'
  PROJECT_NUM: '809358225314'
  REPOSITORY: 'my-docker-repo'
  GITHUB_REPO: 'tutorial-emata-direct-wif2'
jobs:
  get_secret:
    name: Get Secret from Secret Manager
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        workload_identity_provider: 'projects/${{ env.PROJECT_NUM }}/locations/global/workloadIdentityPools/github/providers/${{ env.GITHUB_REPO }}'
        service_account: '${{ env.SERVICE_ACCOUNT_EMAIL }}'
        # GitHub Actions のプリンシパルが サービスアカウントになりすますことを明示。
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Get Secret'
      run: gcloud secrets versions access latest --secret="my-secret"

    - name: 'Build and Push Docker Image'
      run: |
        gcloud builds submit \
          --project=${{ env.PROJECT_ID }} \
          --tag asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/my-image \
          --service-account=${{ env.SERVICE_ACCOUNT_EMAIL }} \
          --gcs-log-dir='gs://${{ env.PROJECT_ID }}_cloudbuild/logs'
