name: Get Secret
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  get_secret:
    name: Get Secret from Secret Manager
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'tutorial-emata-direct-wif'
        workload_identity_provider: 'projects/281608056900/locations/global/workloadIdentityPools/github/providers/tutorial-emata-direct-wif'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Get Secret'
      run: gcloud secrets versions access latest --secret="my-secret"  # シークレットを読み取り。

    - name: 'Build and Push Docker Image'
      run: |
        gcloud builds submit --tag asia-northeast1-docker.pkg.dev/tutorial-emata-direct-wif/my-docker-repo/my-image
